name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Check formatting
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./scadl ./tutorial"
    - name: Check import sorting
      uses: isort/isort-action@v1
      with:
        requirementsFiles: "requirements.txt"
        configuration: "--profile black --check-only --diff"
